### PR TITLE
Calibration Bar with unit

### PR DESCRIPTION
**Pull request by jejmule**
Display the Calibration unit into the Calibration bar

### CODE REVIEW

**Comment by jejmule** [comment]
What do you think about it?

**Comment by ctrueden** [comment]
@rasband What do you think?

**Comment by rasband** [comment]
This code is in the latest ImageJ daily build (1.51q42). You have to check "Show unit" in the dialog box to enable it.

**Comment by ctrueden** [comment]
For reference, the changes can be [seen here](https://github.com/imagej/imagej1/commit/bfefbdbb68cb5202b58be15ece6da95629e54040#diff-3253f3a67c0c2d7d71ed49cd55941dd0).

**Comment by jejmule** [comment]
Good, thanks guy

**Pull request closed without merging**
