### PR TITLE
XY_PlotStack 

### PR DESCRIPTION
**Pull request by jejmule**
This plugin generates a stack of plots with the same vertical scale
Source image is a stack or hyperstack
Line or rectangle ROI is required

This is plugin, I have written for my personal use. I used it in a daily basis and share it with lot of user. I think this function is useful for the entire community.

### CODE REVIEW

**Comment by ctrueden** [comment]
@rasband Do you want to include this "Plot XY Profile" in ImageJ core?

**Comment by rasband** [comment]
This plugin, renamed StackPlotter, is in the latest ImageJ daily build (1.51q46). It implements the new Image>Stacks>Plot XY Profile command.

**Comment by jejmule** [comment]
I am glad to see my code accepted.

**Comment by ctrueden** [comment]
For reference, the relevant code can be [found here](https://github.com/imagej/imagej1/commit/d02d3d75c601344b73393a9bbfb82a117e905910#diff-73b5f4c1922d196f1c68a894524073a2).

**Pull request closed without merging**
