### PR TITLE
Added option to turn off sorting by meta data (DICOM InstanceNumber) when importing image sequence

### PR DESCRIPTION
**Pull request by Sethur**
Currently, when importing an image sequence (via the `FileOpener` plugin), the DICOM tag _InstanceNumber_ is forcefully used for sorting the incoming files if the DICOM format is detected.

This behavior can cause problems with certain sets of DICOM files where the _InstanceNumber_ tag does not reflect the desired import order and where the user expects the standard alphabetical import order.

This changeset adds an option to deactivate sorting by meta data. The default behavior is unchanged to ensure downward compatibility.

### CODE REVIEW

**Comment by rasband** [comment]
The latest ImageJ daily build (1.52f2) adds a 'noMetaSort' option to the options
string of the FolderOpener.open(dir,options) method. This option
disables sorting of DICOM stacks by series number (tag 0020,0011). The following example opens a DICOM series as a virtual stack without sorting by the series number.

 ` imp = FolderOpener.open("/path/to/directory/", "virtual noMetaSort");`

To avoid choice overload, I did not add an option to turn off sorting by metadata to the File>Import>Image Sequence dialog.

View code changes at
https://github.com/imagej/imagej1/commit/3b64d27347c3cbb68356f5a70e952f8cbc624f2d

**Comment by Sethur** [comment]
@rasband For me, this is sufficient, but I think most users will not find this new option, since it will probably not explicitly end up in the documentation (https://imagej.nih.gov/ij/developer/macro/functions.html).

If it's not in the docs, then most users would record a macro to find the necessary options, but here this wouldn't work because you can't trigger noMetaSort via the UI.

**Comment by rasband** [comment]
What I can do is enable, and record, 'noMetaSort' if "Sort names numerically" is not checked in the dialog. Would that work? The images would still be sorted by file names.

**Comment by Sethur** [comment]
@rasband: That would work and hopefully not break backward compatibility since people who just want to import a DICOM folder had no reason to uncheck "Sort names numerically".

**Comment by rasband** [comment]
With the latest ImageJ daily build (1.52f4), the 'noMetaSort' option is triggered (and recorded) if "Sort names numerically" is not checked in the dialog.

**Pull request closed without merging**
